ARG VARIANT=8.4
FROM mcr.microsoft.com/devcontainers/php:${VARIANT}


# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
